In [1]:
import numpy as np
m  = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print m

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [2]:
print 'get element from row 1 and column 0'
print m[1,0]

get element from row 1 and column 0
5


In [3]:
print 'get second row from matrix'
print m[1, :]

get second row from matrix
[[5 6 7 8]]


In [4]:
print 'get third column from matrix'
print m[: , 2]

get third column from matrix
[[3]
 [7]
 [5]]


In [5]:
print 'get elements from second row starting from third element'
print m[1, 2:]

get elements from second row starting from third element
[[7 8]]


In [6]:
print 'get part of column'
print m[0:2, 1]

get part of column
[[2]
 [6]]


In [7]:
print 'get part of matrix'
print m[0:2, 1:3]

get part of matrix
[[2 3]
 [6 7]]


In [9]:
print 'get concrete columns'
cols = [0,1,3]
print m[:, cols]

get concrete columns
[[1 2 4]
 [5 6 8]
 [9 1 7]]
