In [1]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print m

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [2]:
print type(m)

<class 'numpy.matrix'>


In [3]:
print 'convert matrix to ndarray'
m = np.array(m)
print type(m)

convert matrix to ndarray
<type 'numpy.ndarray'>


In [4]:
print m

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [5]:
print m.shape

(3L, 4L)


In [7]:
print m.max()

9


In [8]:
print np.max(m)

9


In [9]:
print 'select max in each row'
print m.max(axis = 1)

select max in each row
[4 8 9]


In [10]:
print 'select max in each column'
print m.max(axis = 0)

select max in each column
[9 6 7 8]


In [11]:
print m.min(axis = 1)

[1 5 1]


In [13]:
print m.sum(axis = 1)

[10 26 22]


In [16]:
print 'multiply element in each row'
print m.prod(axis = 1)

multiply element in each row
[  24 1680  315]


In [17]:
print 'dispersion'
print m.var(axis = 1)

dispersion
[1.25 1.25 8.75]
