In [2]:
import numpy as np
nums = np.array([1,2,3,4,5,6,7,8,9,10])
letters = np.array(['a','b','c','d','a','e','b'])

print nums
print letters

[ 1  2  3  4  5  6  7  8  9 10]
['a' 'b' 'c' 'd' 'a' 'e' 'b']


In [9]:
print 'Using boolean array to get selection'
less_then_5 = nums < 5
print less_then_5

Using boolean array to get selection
[ True  True  True  True False False False False False False]


In [4]:
pos_a = letters == 'a'
print pos_a

[ True False False False  True False False]


In [5]:
nums_less_then_5 = nums[less_then_5]
print nums_less_then_5

[1 2 3 4]


In [6]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print m

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [7]:
mod_m = np.logical_and(m>=3,m<=7)
print mod_m

[[False False  True  True]
 [ True  True  True False]
 [False False  True  True]]


In [8]:
print m[mod_m]

[[3 4 5 6 7 5 7]]


In [10]:
print 'Indexing with boolean expression'
nums = np.array([1,2,3,4,5,6,7,8,9,10])
nums = nums[nums<5]
print nums

Indexing with boolean expression
[1 2 3 4]


In [12]:
nums1 = np.array([1,2,3,4,5,6,7,8,9,10])
nums1[nums1 < 5] = 10
print nums1

[10 10 10 10  5  6  7  8  9 10]
