In [1]:
import numpy as np


In [3]:
print 'create vector'
print np.arange(10)

create vector
[0 1 2 3 4 5 6 7 8 9]


In [4]:
print np.arange(5,12)

[ 5  6  7  8  9 10 11]


In [5]:
print np.arange(1,3,0.2)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]


In [6]:
print 'create matrix'
print '1'
a = [[1,2],[3,4]]
print np.matrix(a)


create matrix
1
[[1 2]
 [3 4]]


In [7]:
print 'create matrix'
print '2'
b = np.array([[5,6],[7,8]])
print np.matrix(b)

create matrix
2
[[5 6]
 [7 8]]


In [8]:
print 'create matrix'
print '3'
print np.matrix('[1,2; 3,4]')

create matrix
3
[[1 2]
 [3 4]]


In [10]:
print 'create matrix with 0 values'
print np.zeros((3,4))

create matrix with 0 values
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
print 'create matrix with  1 values in main diagonal'
print np.eye(3)

create matrix with  1 values in main diagonal
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import numpy as np
print 'Matrix A'
A = np.matrix('[1,2; 3,4]')
print A
print 'Matrix B'
B = np.matrix('[5,6;7,8]')
print B

Matrix A
[[1 2]
 [3 4]]
Matrix B
[[5 6]
 [7 8]]


In [4]:
print 'matrix addition'
print A + B

matrix addition
[[ 6  8]
 [10 12]]


In [5]:
print 'matrix subtraction'
print A - B

matrix subtraction
[[-4 -4]
 [-4 -4]]


In [7]:
print 'matrix multiplication by number'
print 3 * A

matrix multiplication by number
[[ 3  6]
 [ 9 12]]


In [8]:
print 'matrix multiplication'
print A.dot(B)

matrix multiplication
[[19 22]
 [43 50]]


In [9]:
print 'matrix transpose'
print A.T

matrix transpose
[[1 3]
 [2 4]]


In [10]:
print 'matrix transpose 2'
print np.transpose(A)

matrix transpose 2
[[1 3]
 [2 4]]
