In [2]:
import numpy as np

In [3]:
print 'Vector'
v_hor_np = np.array([1,2])
print v_hor_np

Vector
[1 2]


In [4]:
print 'Vector with 0 values'
v_hor_zeros_v1 = np.zeros((5,))
print v_hor_zeros_v1

Vector with 0 values
[0. 0. 0. 0. 0.]


In [5]:
print 'Vector with 1 values'
v_hor_one_v1 = np.ones(5,)
print v_hor_one_v1

Vector with 1 values
[1. 1. 1. 1. 1.]


In [6]:
print 'Vector column'
v_vert_np = np.array([[1],[2]])
print v_vert_np

Vector column
[[1]
 [2]]


In [7]:
print 'Vector column with 0 value'
v_vert_zeros = np.zeros((5,1))
print v_vert_zeros

Vector column with 0 value
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [8]:
print 'Vector column with 1 value'
v_vert_ones = np.ones((5,1))
print v_vert_ones

Vector column with 1 value
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [9]:
print 'square matrix'
m_sqr_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print m_sqr_arr

square matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print 'square matrix'
m_sqr_mx = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print m_sqr_mx

square matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print 'square matrix'
m_sqr_mx = np.matrix('1 2 3;4 5 6;7 8 9')
print m_sqr_mx

square matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print 'diagonal matrix'
m_diag = [[1,0,0],[0,5,0],[0,0,9]]
m_diag_np = np.matrix(m_diag)
print m_diag_np

diagonal matrix
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [13]:
print 'diagonal matrix'
m_sqr_mx = np.matrix('1 2 3;4 5 6;7 8 9')
diag = np.diag(m_sqr_mx)
print diag

diagonal matrix
[1 5 9]


In [14]:
m_diag_np = np.diag(np.diag(m_sqr_mx))
print m_diag_np

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [15]:
print 'unit matrix'
m_e = [[1,0,0], [0,1,0],[0,0,1]]
m_e_np = np.matrix(m_e)
print m_e_np

unit matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
print 'unit matrix'
m_eye = np.eye(3)
print m_eye

unit matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
print 'zeros matrix'
n_zeros = np.zeros((3,3))
print n_zeros

zeros matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
