In [1]:
import numpy as np
A = np.matrix('1 2 3; 4 5 6')
print A

[[1 2 3]
 [4 5 6]]


In [3]:
print 'transposed matrix'
A_t = A.transpose()
print A_t

transposed matrix
[[1 4]
 [2 5]
 [3 6]]


In [4]:
print 'transposed matrix'
print A.T

transposed matrix
[[1 4]
 [2 5]
 [3 6]]


In [6]:
print 'double transposed matrix'
B = np.matrix('1 2 3; 4 5 6')
R = (B.T).T
print R

double transposed matrix
[[1 2 3]
 [4 5 6]]


In [8]:
print 'transpose matrix sum'
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8 9; 0 7 5')

L = (A + B).T
print L

R = A.T + B.T
print R

transpose matrix sum
[[ 8  4]
 [10 12]
 [12 11]]
[[ 8  4]
 [10 12]
 [12 11]]


In [9]:
print 'transpose matrix multiplication'
A = np.matrix('1 2;3 4')
B = np.matrix('5 6;7 8')

L = (A.dot(B)).T
print L

R = (B.T).dot(A.T)
print R

transpose matrix multiplication
[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


In [10]:
print 'Transpose the multiplication of the matrix by a number'
A = np.matrix('1 2 3; 4 5 6')
k = 3

L = (k * A).T
print L

R = k * (A.T)
print R

Transpose the multiplication of the matrix by a number
[[ 3 12]
 [ 6 15]
 [ 9 18]]
[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [12]:
print 'determinant of transpose matrix'
A = np.matrix('1 2; 3 4')

A_det = np.linalg.det(A)
print A_det

A_T_det = np.linalg.det(A.T)
print A_T_det

determinant of transpose matrix
-2.0000000000000004
-2.0
