In [1]:
print 'multiply matrix by number'
import numpy as np
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print C

multiply matrix by number
[[ 3  6  9]
 [12 15 18]]


In [2]:
A = np.matrix('1 2 3; 4 5 6')
D = 0 * A
print D

[[0 0 0]
 [0 0 0]]


In [3]:
print 'multiply matrix by the sum of numbers'
A = np.matrix('1 2;3 4')
p = 2
q = 3

L = (p + q) * A
R = p*A + q*A

print L
print R

multiply matrix by the sum of numbers
[[ 5 10]
 [15 20]]
[[ 5 10]
 [15 20]]


In [4]:
print 'multiply matrix by the multiply of two numbers'
A = np.matrix('1 2; 3 4')
p = 2
q = 3

L = (p*q) * A
R = p * (q*A)

print L
print R

multiply matrix by the multiply of two numbers
[[ 6 12]
 [18 24]]
[[ 6 12]
 [18 24]]


In [5]:
print 'matrix addition'
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')

C = A + B
print C

matrix addition
[[ 9  7  8]
 [14 11 19]]


In [6]:
print 'Addition commutativity'
A = np.matrix('1 2; 3 4')
B = np.matrix('4 5; 6 7')

C = A + B
D = B + A
print C
print D

Addition commutativity
[[ 5  7]
 [ 9 11]]
[[ 5  7]
 [ 9 11]]


In [7]:
print 'Associativity addition'
A = np.matrix('1 2;3 4')
B = np.matrix('5 6;7 8')
C = np.matrix('1 7;9 3')

L = A + (B + C)
R = (A + B) + C
print L
print R

Associativity addition
[[ 7 15]
 [19 15]]
[[ 7 15]
 [19 15]]


In [10]:
print 'Inverse matrix'
A = np.matrix('1 2;3 4')
print A
B = (-1) * A
print B

C = A + B
print C

Inverse matrix
[[1 2]
 [3 4]]
[[-1 -2]
 [-3 -4]]
[[0 0]
 [0 0]]


In [11]:
print 'multiply matrixes'
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')

C = A.dot(B)
print C

multiply matrixes
[[31 19]
 [85 55]]


In [12]:
print 'Associativity multiply'
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')

L = A.dot(B.dot(C))
print L

R = (A.dot(B)).dot(C)
print R

Associativity multiply
[[192 252]
 [436 572]]
[[192 252]
 [436 572]]


In [14]:
print 'Distributivity multiply'
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')

L = A.dot(B + C)
R= A.dot(B) + A.dot(C)
print L
print R

Distributivity multiply
[[35 42]
 [77 94]]
[[35 42]
 [77 94]]


In [15]:
print 'Commutativity of matrixes'
A = np.matrix('1 2;3 4')
B = np.matrix('4 5;6 7')

L = A.dot(B)
R = B.dot(A)

print 'L != R'
print L
print R

Commutativity of matrixes
L != R
[[16 19]
 [36 43]]
[[19 28]
 [27 40]]


In [16]:
print 'unit matrix multiplication'
A = np.matrix('1 2;3 4')
B = np.matrix('1 0;0 1')

L = B.dot(A)
R = A.dot(B)

print L
print R

unit matrix multiplication
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
