In [2]:
print 'determinant of matrix'
import numpy as np
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print A
det = np.linalg.det(A)
print det

determinant of matrix
[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
-14.000000000000009


In [5]:
print '1. determinant of matrix and transpose of matrix'
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print A
print A.T
det_A = round(np.linalg.det(A),3)
det_A_t = round(np.linalg.det(A.T),3)

print det_A
print det_A_t

1. determinant of matrix and transpose of matrix
[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]
-14.0
-14.0


In [6]:
print '2. determinant of matrix and row with zeros'
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
det_A = np.linalg.det(A)
print det_A

2. determinant of matrix and row with zeros
0.0


In [8]:
print '3. determinant of matrix and replacement of rows'

A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print A
print B

det_A = round(np.linalg.det(A),3)
det_B = round(np.linalg.det(B),3)
print det_A
print det_B

3. determinant of matrix and replacement of rows
[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]
-14.0
14.0


In [9]:
print '4. determinant of matrix and two identical rows'
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
det_A = np.linalg.det(A)
print det_A

4. determinant of matrix and two identical rows
0.0
