In [2]:
print 'inverse matrix'
import numpy as np
A = np.matrix('1 -3;2 5')
A_inv = np.linalg.inv(A)
print A_inv

inverse matrix
[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [3]:
print 'inverse matrix of inverse matrix'
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print A
print A_inv_inv

inverse matrix of inverse matrix
[[ 1. -3.]
 [ 2.  5.]]
[[ 1. -3.]
 [ 2.  5.]]


In [5]:
print 'rank matrix'
m_eye = np.eye(4)
print m_eye

rank = np.linalg.matrix_rank(m_eye)
print rank

rank matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4


In [6]:
print 'rank matrix'
m_eye = np.eye(4)
m_eye[3][3] = 0
print m_eye

rank = np.linalg.matrix_rank(m_eye)
print rank

rank matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]]
3


In [7]:
print 'rank matrix'
m = np.matrix('1 2 3; 1 2 3; 4 5 6')
print m

rank = np.linalg.matrix_rank(m)
print rank

rank matrix
[[1 2 3]
 [1 2 3]
 [4 5 6]]
2
